CREATE TABLE ALUNO
(
	ra VARCHAR (10) NOT NULL,
	nome VARCHAR (50) NOT NULL,
	cpf VARCHAR (14) NOT NULL,
	data_nasc DATE NOT NULL,
	telfone VARCHAR (14) NOT NULL,
	localidade VARCHAR (50) NOT NULL,
	logradouro VARCHAR (50) NOT NULL,
	numero INT NOT NULL,
	cep VARCHAR (10) NOT NULL,
	bairro VARCHAR (50) NOT NULL,
	uf CHAR (2) NOT NULL,
	complemento VARCHAR(30) NULL,
	CONSTRAINT PK_ALUNO PRIMARY KEY (ra),
	UNIQUE (cpf)
)
CREATE TABLE DISCIPLINA
(
	codigo INT IDENTITY (1,1) NOT NULL,
	nome VARCHAR (50) NOT NULL,
	qtd_aulas INT NOT NULL,
	CONSTRAINT PK_DISCIPLINA PRIMARY KEY (codigo)
)
CREATE TABLE [STATUS]
(
	codigo SMALLINT NOT NULL,
	descricao VARCHAR (20) NOT NULL
	CONSTRAINT PK_STATUS PRIMARY KEY (codigo)
)

INSERT [STATUS]
VALUES (1,'APROVADO'),(2,'RECUPERAÇÃO'),(3, 'REPROVADO POR NOTA'),(4, 'REPROVADO POR FALTA')

CREATE TABLE MATRICULA
(
	ano INT NOT NULL,
	semestre INT NOT NULL,
	nota1 DECIMAL(4, 2) NULL,
	nota2 DECIMAL(4, 2) NULL,
	substitutiva DECIMAL(4, 2) NULL,
	media DECIMAL(4, 2) NULL,
	numero_faltas INT NOT NULL,
	ra_aluno VARCHAR (10) NOT NULL,
	codigo_status SMALLINT NOT NULL,
	codigo_disciplina INT NOT NULL,
	CONSTRAINT PK_MATRICULA PRIMARY KEY (ra_aluno, codigo_disciplina),
	CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (ra_aluno) REFERENCES Aluno(ra),
	CONSTRAINT FK_MATRICULA_DISCIPLINA FOREIGN KEY (codigo_disciplina) REFERENCES Disciplina(codigo),
	CONSTRAINT FK_MATRICULA_STATUS FOREIGN KEY (codigo_status) REFERENCES [Status] (codigo)
)

